version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=loco
      - POSTGRES_PASSWORD=loco
      - POSTGRES_DB=xq-sns-app_test
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loco -d xq-sns-app_test"]
      interval: 10s
      timeout: 5s
      retries: 5
