name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  # Setup and run checks using Moonrepo
  check:
    name: Run All Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: loco
          POSTGRES_PASSWORD: loco
          POSTGRES_DB: xq-sns-app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Moonrepo toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            xq-sns-app -> target
            PLocoBuf -> target

      - name: Install frontend dependencies
        run: |
          cd xq-sns-app/frontend
          npm install

      # Format checks
      - name: Run format checks
        run: |
          moon run xq-sns-app:fmt
          moon run PLocoBuf:fmt
          moon run frontend:lint

      # Clippy checks
      - name: Run Clippy
        run: |
          moon run xq-sns-app:clippy
          moon run PLocoBuf:clippy

      # Build frontend
      - name: Build frontend
        run: moon run frontend:build

      # Run tests
      - name: Run tests
        run: moon run xq-sns-app:test
        env:
          DATABASE_URL: postgres://loco:loco@localhost:5432/xq-sns-app_test
